import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  weight: ['100', '200', '400', '500', '600', '800']
})

export const metadata = {
  title: {
    default: "Hero Kidz",
    template: "%s | Hero Kidz",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <header className="w-11/12 mx-auto">
          <Navbar></Navbar>
        </header>
        <main className="bg-zinc-50 px-8 py-11"> {children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
